# Site Settings
name: "Mageplaza"
title: "Mageplaza"
slogan: "The Magento Store"
description: "Build it your way"
email: "support@mageplaza.com"
url: "https://www.mageplaza.com"
baseurl: "https://www.mageplaza.com"
domain: "mageplaza.com"
author: "mageplaza"
this_year: "2016"

paypal: "haitv282@gmail.com"

google_verify: "mqeRPCxfPDdd8Ai589_r1ylvomMFyjYC0epneqbK74"
bing_verify: 
google_analytics:   

# Social accounts
google_plus: ""
disqus_shortname: "mageplaza"

subcriber_url: "http://t.us3.list-manage1.com/subscribe/post?u=531af730d34352cf489&amp;id=0416bef2d9"

# Build Settings
markdown: kramdown
encoding: UTF-8

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  # toc_levels: 1..6
  # enable_coderay: true

  # coderay:
  #   coderay_line_numbers: nil
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

# http://jekyllrb.com/docs/permalinks/
# /:title/ /:title.html
permalink:   "/:categories/:slug.html/"

# Amount of post to show on home page
paginate: 10
paginate_path: "/blog/page:num/"

future:      true
highlighter: rouge

gems:
  # - jekyll-redirect-from
  # http://jekyllrb.com/docs/templates/#gist
  # - jekyll-gist


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor"]


collections:
  magento-extensions:
    output: true
  magento2:
    output: true
  pages:
    output: true
  kb:
    output: true
